//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViajemosEntities : DbContext
    {
        public ViajemosEntities()
            : base("name=ViajemosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<autores> autores { get; set; }
        public virtual DbSet<editoriales> editoriales { get; set; }
        public virtual DbSet<libros> libros { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
